### ISSUE TITLE
Creating mapping from cassandra table fails on float value

### ISSUE THREAD

**Issue by albroscani** [strapdata/elassandra#17] opened 2016-05-03 09:59 UTC
Hi Vincent,
I've created a table in Cassandra with several data types (text, timestamp, bigint, double, boolean, float) and I've done a synchronization to create a Mapping in Elasticsearch with CURL 

`
curl -XPUT "http://localhost:9200/my_keyspace/_mapping/my_table" -d '{ 
    "my_table" : { 
        "columns_regexp" : "a.*",
        "properties" : {
            "name" : {
                "type" : "string",
                "index" : "not_analyzed"
            }
        }
    }
}'
`

All fields are mapped well except the FLOAT value (I can't see the value querying Elasticsearch where the field exists but empty).

Let me know if you are able to reproduce the issue.
Thanks,

Alberto

**Comment by vroyer** [comment] 2016-05-03 22:35
Hi Alberto,
Sorry but i can't reproduce this issue, float colum is correctly mapped to a float field in elasticsearch.
Could you share your cassandra schema or check your logs (debug level can be set in conf/logback.xml).
Thanks,
Vincent.

**Comment by albroscani** [comment] 2016-05-10 10:09
Hi Vincent,
sorry for the delay. The float column is correctly mapped  to a float field in elasticsearch but when I try to discover the values of the index in Kibana the float value is not returned by Elasticsearch.
Let me know if you are able to reproduce this issue and if you need other details.
Thanks,
Alberto

**Comment by vroyer** [comment] 2016-05-10 23:22
Fixed in release 2.1.1-9 (float was not implemented in the internal cassandra query, change in org/apache/cassandra/cql3/UntypedResultSet.java )

**Closed as completed by vroyer** 2016-05-10 23:22 UTC
