### ISSUE TITLE
Question. Is there a workaround for empty object type?

### ISSUE THREAD

**Issue by sergibondarenko** [strapdata/elassandra#146] opened 2017-12-06 13:36 UTC
[The elassandra doc](http://elassandra.readthedocs.io/en/latest/limitations.html#nested-or-object-types-cannot-be-empty) says: "Because Elasticsearch nested and object types are backed by a Cassandra User Defined Type, it requires at least one sub-field in the mapping.";

My app currently works with Elasticsearch v5+ and v6+ and [object type](https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html) mapping is used.

For example
```
{
  "properties": {
    "input": {
      "type": "object",
      "enabled": false
    }
  }
}
```

There are fields where I have a lot of deeply nested objects I don't know beforehand their names or the level of deepness. For example, the `input` above has to support any Elasticsearch query syntax.
```
{
  "properties": {
    "search": {
      "query": {
        Elasticsearch query is here
      }
    }
  }
}
```

That's why I need to add the new properties dynamically to the `input`. 

Is there any workaround to support my case? 

PS
I know that the property can be stringified.

**Comment by vroyer** [comment] 2017-12-06 21:32
I’m not sure to understand your issue.
Disabled fields are stored in a C* text columns, this is JSON not interpreted by elasticsearch, so in this case, there is no UDT involved at all, and it can be as deep as you want, this is just a string form C* and ES.
(See org.elassandra.ObjectNotEnabledTests.java for example)
Does this clarify the topic for you ?

**Comment by sergibondarenko** [comment] 2017-12-07 10:57
@vroyer 
The actual error I get is
```
elassandra-kibana    | {"type":"log","@timestamp":"2017-12-07T08:27:03Z","tags":["status","error","Sentinl"],"pid":12,"message":"[i_o_exception] Cannot create an empty nested type (not supported)"}
```
And I found where the problem is. In one of my mappings I have [enabled: true](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/enabled.html) (default). And this prevents me to create index. 
```
  "properties": {
    "payload": {
      "type": "object"
    }
  }
}
```
I can create the index if I put `enabled: false` under `payload`.
```
  "properties": {
    "payload": {
      "type": "object",
      "enabled": false
    }
  }
}
```
But this prevents me to index `payload` data and I'll not be able to query it. Is there any workaround to have the `payload` data indexed?

**Comment by sergibondarenko** [comment] 2017-12-07 11:07
@vroyer You can use the following JavaScript code to reproduce the issue. Run it like this `node script.js`

```
const Elasticsearch = require('elasticsearch');

const es = {
  host: 'localhost',
  index: 'spaceship',
  port: 9200,
  log: 'trace'
};

const mappings = {
  mappings: {
    'ship-engine': {
      properties: {
        input: {
          type: 'object'
        }
      }
    }
  }
};

const client = new Elasticsearch.Client({
  host: `${es.host}:${es.port}`,
  log: es.log
});

client.indices.exists({
  index: es.index
})  
.then(function(exists) {
  if (exists) {
    console.log('SUCCESS', `Index ${es.index} already exists!`);
    return null;
  }   

  return client.indices.create({
    index: es.index,
    body: mappings
  })  
  .then(function(response) {
    console.log('SUCCESS', response);
  });
})  
.catch(function(error) {
  console.log('FAIL', error);
});
```

Result:
```
FAIL { Error: [i_o_exception] Cannot create an empty nested type (not supported)
    at respond (/home/trex/dev/kibi/elassandra_test/node_modules/elasticsearch/src/lib/transport.js:307:15)
    at checkRespForFailure (/home/trex/dev/kibi/elassandra_test/node_modules/elasticsearch/src/lib/transport.js:266:7)
    at HttpConnector.<anonymous> (/home/trex/dev/kibi/elassandra_test/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/home/trex/dev/kibi/elassandra_test/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  status: 500,
  displayName: 'InternalServerError',
  message: '[i_o_exception] Cannot create an empty nested type (not supported)',
  path: '/spaceship',
  query: {},
  body: 
   { error: 
      { root_cause: [Object],
        type: 'i_o_exception',
        reason: 'Cannot create an empty nested type (not supported)',
        caused_by: [Object] },
     status: 500 },
  statusCode: 500,
  response: '{"error":{"root_cause":[{"type":"i_o_exception","reason":"Cannot create an empty nested type (not supported)"}],"type":"i_o_exception","reason":"Cannot create an empty nested type (not supported)","caused_by":{"type":"invalid_request_exception","reason":"Cannot create an empty nested type (not supported)"}},"status":500}',
  toString: [Function],
  toJSON: [Function] }
```

Expected result
```
SUCCESS { acknowledged: true,
  shards_acknowledged: true,
  index: 'spaceship' }

```

**Comment by vroyer** [comment] 2017-12-07 11:55
Ok, but why do you create an empty object with enable=true ? 
Is it to later add sub-field in that object ?

**Comment by sergibondarenko** [comment] 2017-12-07 13:08
@vroyer I create it to add multiple sub-fields.

**Comment by vroyer** [comment] 2017-12-07 13:19
The issue comes from Cassandra because an UDT must have at lear on sub-field.
So I can delay the creation of the C* UDT type till there is at least one subfield.

**Comment by vroyer** [comment] 2017-12-07 22:52
I have released a fix on branch #146-branch

**Comment by lmangani** [comment] 2017-12-09 18:30
Building a release to validate outcome and will report here, thanks @vroyer

**Comment by lmangani** [comment] 2017-12-10 10:42
On Create:

```
elassandra-kibana    | {"type":"log","@timestamp":"2017-12-10T10:20:22Z","tags":["status","error","Sentinl"],"pid":12,"message":"[index_not_found_exception] no such index, with { resource.type=\"index_or_alias\" & resource.id=\"watcher\" & index_uuid=\"_na_\" & index=\"watcher\" }"}

elassandra-seed-node | 2017-12-10 10:20:22,805 INFO  [elasticsearch[172.26.0.2][clusterService#updateTask][T#1]] org.apache.cassandra.service.StorageService.setLoggingLevel(StorageService.java:3817) set log level to TRACE for classes under 'index.search.slowlog.query.watcher_alarms' (if the level doesn't look like 'TRACE' then the logger couldn't parse 'TRACE')

elassandra-seed-node | 2017-12-10 10:20:22,806 INFO  [elasticsearch[172.26.0.2][clusterService#updateTask][T#1]] org.apache.cassandra.service.StorageService.setLoggingLevel(StorageService.java:3817) set log level to TRACE for classes under 'index.search.slowlog.fetch.watcher_alarms' (if the level doesn't look like 'TRACE' then the logger couldn't parse 'TRACE')

elassandra-seed-node | 2017-12-10 10:20:22,811 INFO  [elasticsearch[172.26.0.2][clusterService#updateTask][T#1]] org.apache.cassandra.service.MigrationManager.announceNewKeyspace(MigrationManager.java:310) Create new Keyspace: KeyspaceMetadata{name=watcher_alarms, params=KeyspaceParams{durable_writes=true, replication=ReplicationParams{class=org.apache.cassandra.locator.NetworkTopologyStrategy, DC1=1}}, tables=[], views=[], functions=[], types=[]}

elassandra-seed-node | 2017-12-10 10:20:23,190 WARN  [elasticsearch[172.26.0.2][clusterService#updateTask][T#1]] org.elasticsearch.cluster.service.ClusterService.updateTableSchema(ClusterService.java:1244) Ignoring enabled object with no sub-fields
```

On Writes:
```
elassandra-kibana    | {"type":"log","@timestamp":"2017-12-10T10:24:32Z","tags":["status","info","Sentinl"],"pid":12,"message":"Saving Watcher with ID: dqu5lvjnav7-ba1pmznqeu4-cudsrw0hs7o"}

elassandra-seed-node | 2017-12-10 10:24:32,545 INFO  [elasticsearch[172.26.0.2][clusterService#updateTask][T#1]] org.apache.cassandra.service.StorageService.setLoggingLevel(StorageService.java:3817) set log level to TRACE for classes under 'index.search.slowlog.query.watcher' (if the level doesn't look like 'TRACE' then the logger couldn't parse 'TRACE')

elassandra-seed-node | 2017-12-10 10:24:32,546 INFO  [elasticsearch[172.26.0.2][clusterService#updateTask][T#1]] org.apache.cassandra.service.StorageService.setLoggingLevel(StorageService.java:3817) set log level to TRACE for classes under 'index.search.slowlog.fetch.watcher' (if the level doesn't look like 'TRACE' then the logger couldn't parse 'TRACE')

elassandra-seed-node | 2017-12-10 10:24:32,558 WARN  [elasticsearch[172.26.0.2][bulk][T#2]] org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:133) path: /watcher/sentinl-watcher/dqu5lvjnav7-ba1pmznqeu4-cudsrw0hs7o, params: {index=watcher, id=dqu5lvjnav7-ba1pmznqeu4-cudsrw0hs7o, type=sentinl-watcher}

elassandra-seed-node | org.elasticsearch.transport.RemoteTransportException: [172.26.0.2][172.26.0.2:9300][indices:data/write/bulk[s][p]]

elassandra-seed-node | Caused by: org.elasticsearch.common.util.concurrent.UncategorizedExecutionException: Failed execution
elassandra-seed-node | 	at org.elasticsearch.action.support.AdapterActionFuture.rethrowExecutionException(AdapterActionFuture.java:93)
elassandra-seed-node | 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:47)
elassandra-seed-node | 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
elassandra-seed-node | 	at org.elasticsearch.cluster.action.index.MappingUpdatedAction.updateMappingOnMaster(MappingUpdatedAction.java:89)
elassandra-seed-node | 	at org.elasticsearch.cluster.action.index.MappingUpdatedAction.updateMappingOnMaster(MappingUpdatedAction.java:80)
elassandra-seed-node | 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:476)
elassandra-seed-node | 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:150)
elassandra-seed-node | 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
elassandra-seed-node | 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:72)
elassandra-seed-node | 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:965)
elassandra-seed-node | 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:934)
elassandra-seed-node | 	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113)
elassandra-seed-node | 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:291)
elassandra-seed-node | 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
elassandra-seed-node | 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:260)
elassandra-seed-node | 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:252)
elassandra-seed-node | 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
elassandra-seed-node | 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:656)
elassandra-seed-node | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
elassandra-seed-node | 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
elassandra-seed-node | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
elassandra-seed-node | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
elassandra-seed-node | 	at java.lang.Thread.run(Thread.java:748)
elassandra-seed-node | Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Unknown type watcher.sentinl_watcher_input_search_request
elassandra-seed-node | 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:262)
elassandra-seed-node | 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:249)
elassandra-seed-node | 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:91)
elassandra-seed-node | 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42)
elassandra-seed-node | 	... 21 common frames omitted
elassandra-seed-node | Caused by: java.io.IOException: Unknown type watcher.sentinl_watcher_input_search_request
elassandra-seed-node | 	at org.elasticsearch.cluster.service.ClusterService.updateTableSchema(ClusterService.java:1383)
elassandra-seed-node | 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:387)
elassandra-seed-node | 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:268)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.BaseClusterService.executeTasks(BaseClusterService.java:631)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.BaseClusterService.calculateTaskOutputs(BaseClusterService.java:608)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.BaseClusterService.runTasks(BaseClusterService.java:567)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.BaseClusterService$ClusterServiceTaskBatcher.run(BaseClusterService.java:263)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.BaseClusterService$ClusterServiceTaskBatcher$UpdateTask.run(BaseClusterService.java:266)
elassandra-seed-node | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
elassandra-seed-node | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247)
elassandra-seed-node | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210)
elassandra-seed-node | 	... 3 common frames omitted
elassandra-seed-node | Caused by: org.apache.cassandra.exceptions.InvalidRequestException: Unknown type watcher.sentinl_watcher_input_search_request
elassandra-seed-node | 	at org.apache.cassandra.cql3.CQL3Type$Raw$RawUT.prepare(CQL3Type.java:768)
elassandra-seed-node | 	at org.apache.cassandra.cql3.CQL3Type$Raw$RawCollection.prepare(CQL3Type.java:684)
elassandra-seed-node | 	at org.apache.cassandra.cql3.CQL3Type$Raw$RawCollection.prepare(CQL3Type.java:651)
elassandra-seed-node | 	at org.apache.cassandra.cql3.CQL3Type$Raw.prepare(CQL3Type.java:530)
elassandra-seed-node | 	at org.apache.cassandra.cql3.statements.CreateTypeStatement.createType(CreateTypeStatement.java:116)
elassandra-seed-node | 	at org.apache.cassandra.cql3.statements.CreateTypeStatement.announceMigration(CreateTypeStatement.java:130)
elassandra-seed-node | 	at org.apache.cassandra.cql3.statements.SchemaAlteringStatement.execute(SchemaAlteringStatement.java:93)
elassandra-seed-node | 	at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:224)
elassandra-seed-node | 	at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:255)
elassandra-seed-node | 	at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:270)
elassandra-seed-node | 	at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:265)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.ClusterService.buildUDT(ClusterService.java:980)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.ClusterService.buildCql(ClusterService.java:880)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.ClusterService.buildUDT(ClusterService.java:910)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.ClusterService.buildCql(ClusterService.java:880)
elassandra-seed-node | 	at org.elasticsearch.cluster.service.ClusterService.updateTableSchema(ClusterService.java:1278)
elassandra-seed-node | 	... 15 common frames omitted
elassandra-kibana    | {"type":"error","@timestamp":"2017-12-10T10:24:32Z","tags":[],"pid":12,"level":"error","message":"[uncategorized_execution_exception] Failed execution","error":{"message":"[uncategorized_execution_exception] Failed execution","name":"Error","stack":"[uncategorized_execution_exception] Failed execution :: {\"path\":\"/watcher/sentinl-watcher/dqu5lvjnav7-ba1pmznqeu4-cudsrw0hs7o\",\"query\":{},\"body\":\"{\\\"title\\\":\\\"watcher_title\\\",\\\"disable\\\":false,\\\"report\\\":false,\\\"trigger\\\":{\\\"schedule\\\":{\\\"later\\\":\\\"every 1 mins\\\"}},\\\"input\\\":{\\\"search\\\":{\\\"request\\\":{\\\"index\\\":[],\\\"body\\\":{}}}},\\\"condition\\\":{\\\"script\\\":{\\\"script\\\":\\\"payload.hits.total > 100\\\"}},\\\"actions\\\":{\\\"email_admin\\\":{\\\"throttle_period\\\":\\\"0h15m0s\\\",\\\"email\\\":{\\\"to\\\":\\\"alarm@localhost\\\",\\\"from\\\":\\\"sentinl@localhost\\\",\\\"subject\\\":\\\"Sentinl Alarm\\\",\\\"priority\\\":\\\"high\\\",\\\"body\\\":\\\"Found {{payload.hits.total}} Events\\\"}}},\\\"transform\\\":{}}\",\"statusCode\":500,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"uncategorized_execution_exception\\\",\\\"reason\\\":\\\"Failed execution\\\"}],\\\"type\\\":\\\"uncategorized_execution_exception\\\",\\\"reason\\\":\\\"Failed execution\\\",\\\"caused_by\\\":{\\\"type\\\":\\\"execution_exception\\\",\\\"reason\\\":\\\"java.io.IOException: Unknown type watcher.sentinl_watcher_input_search_request\\\",\\\"caused_by\\\":{\\\"type\\\":\\\"i_o_exception\\\",\\\"reason\\\":\\\"Unknown type watcher.sentinl_watcher_input_search_request\\\",\\\"caused_by\\\":{\\\"type\\\":\\\"invalid_request_exception\\\",\\\"reason\\\":\\\"Unknown type watcher.sentinl_watcher_input_search_request\\\"}}}},\\\"status\\\":500}\"}\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:295:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:254:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\n    at IncomingMessage.bound (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/api/sentinl/watcher/dqu5lvjnav7-ba1pmznqeu4-cudsrw0hs7o","path":"/api/sentinl/watcher/dqu5lvjnav7-ba1pmznqeu4-cudsrw0hs7o","href":"/api/sentinl/watcher/dqu5lvjnav7-ba1pmznqeu4-cudsrw0hs7o"}}
elassandra-kibana    | {"type":"response","@timestamp":"2017-12-10T10:24:32Z","tags":[],"pid":12,"method":"post","statusCode":500,"req":{"url":"/api/sentinl/watcher/dqu5lvjnav7-ba1pmznqeu4-cudsrw0hs7o","method":"post","headers":{"host":"xxxx:19061","connection":"keep-alive","content-length":"540","accept":"application/json, text/plain, */*","origin":"http://xxxx:19061","kbn-version":"5.5.0","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36","content-type":"application/json;charset=UTF-8","dnt":"1","referer":"http://xxxx:19061/app/sentinl","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9"},"remoteAddress":"xxxx","userAgent":"xxxx","referer":"http://xxxx:19061/app/sentinl"},"res":{"statusCode":500,"responseTime":50,"contentLength":9},"message":"POST /api/sentinl/watcher/dqu5lvjnav7-ba1pmznqeu4-cudsrw0hs7o 500 50ms - 9.0B"}

```


Mind we're not expecting you to resolve this for us necessarily, rather suggest how we can modify our App queries to work around those limitations and be compatible with both, if possible, or swap to more generic methods - SENTINL (the App generating the interaction here) has thousands of deployments on regular ES (everything in between 4.x, 5.x) without issues and its considered stable. 

Any comment appreciated - Thanks for your time in advance!

PS: Test release used above was created with [this](https://github.com/lmangani/docker-elassandra-builder)

**Comment by vroyer** [comment] 2017-12-10 12:04
Hi Lorenzo,

There’s a mapping issue with type watcher.sentinl_watcher_input_search_request
Would you have your CQL schema and ES mapping for watcher ?

Thanks.
Vincent.

**Comment by lmangani** [comment] 2017-12-10 13:20
Hi Vincent, sure - all our mappings are available fore review here: https://github.com/sirensolutions/sentinl-private/tree/master/server/mappings

**Comment by vroyer** [comment] 2017-12-10 13:40
Sorry, this repo is private.

**Comment by lmangani** [comment] 2017-12-10 13:58
Sorry wrong paste indeed. https://github.com/sirensolutions/sentinl/tree/master/server/mappings

**Comment by vroyer** [comment] 2017-12-10 14:18
Ok, i got it !
There is no document type « watcher » , how can reproduce your issue ?

**Comment by lmangani** [comment] 2017-12-10 15:13
Sure - the below compose should reproduce it, using this sequence:

* start the containers in foreground with ```docker-compose up``` 
* wait for Kibana to come alive _(logs will show SENTINL creating indices, etc)_
* open Kibana, switch to SENTINL App (Clock Icon)
* Add a New Alert w/ defaults, and click SAVE (top right)

**The same error in the report should appear on any save/edit actions.**

_NOTE: I've used a local image build from the Fix Branch for the Elassandra container, sent a PR to gradle build it but I think you'll trust your own best_

```
version: '2.1'
services:
  elassandra-seed:
    container_name: elassandra-seed-node
    image: strapdata/elassandra:5.5.0.8
    ports:
      - "9042:9042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients
      - "9200:9200"   # ES clients
    healthcheck:
        test: cqlsh -e "?" --cqlversion="3.4.4"
        interval: 5s
        timeout: 10s
        retries: 10

  elassandra-kibana:
    container_name: elassandra-kibana
    image: qxip/kibana-steroids:master
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elassandra-seed:9200"
      - "XPACK_MONITORING_ENABLED=false"
      - "SERVER_NAME=ELASSANDRAK"
    depends_on:
      elassandra-seed:
        condition: service_healthy
```

I'm available to join you anytime if useful - Thanks in advance!

**Comment by vroyer** [comment] 2017-12-10 15:34
Watcher, is a kibana 5.5+ plugin that should work with elassandra ?
So i can install this plugin for kibana 5.5 to test it ?

kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.5/sentinl-v5.5.1.zip

**Comment by lmangani** [comment] 2017-12-10 15:37
@vroyer correct, absolutely. We should have releases for all versions of Kibana on the repository.

Just to be clear, SENTINL is working entirely inside Kibana and does not require the Elasticsearch Watcher plugin, xpack crap, etc. It *should* work fine with Elassandra as it only stores/reads from the ES API its own data but we do make some dynamic usage as you will see. Happy to adjust things on our to support both should plain compatibility not be possible, too.

**Comment by vroyer** [comment] 2017-12-11 01:28
Hi Lorenzo,

I have reproduced your issue with sentinl and partially fixed it on branch #146.
You can now save watcher or report definition, but there is still an issue when executing a watcher. 
Sentinl try to write an alert in index  watcher_alarms-2017.12.11 in a dedicated document type ra9k12g85xo-1qd0zo4yjd5-2t4jv1527id_alerte with a field « message », but elasticsearch complains because there is already a message field in this index (type report_admin).

This is a pure elasticsearch check, so i don’t know how this can works with elasticsearch 5.5.0 ?

java.lang.IllegalArgumentException: [message] is defined as a field in mapping [ra9k12g85xo-1qd0zo4yjd5-2t4jv1527id_alerte] but this name is already used for an object in other types
        at org.elasticsearch.index.mapper.MapperService.checkFieldUniqueness(MapperService.java:709)
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:540)
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:482)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:414)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:353)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:268)
        at org.elasticsearch.cluster.service.BaseClusterService.executeTasks(BaseClusterService.java:631)
        at org.elasticsearch.cluster.service.BaseClusterService.calculateTaskOutputs(BaseClusterService.java:608)
        at org.elasticsearch.cluster.service.BaseClusterService.runTasks(BaseClusterService.java:567)
        at org.elasticsearch.cluster.service.BaseClusterService$ClusterServiceTaskBatcher.run(BaseClusterService.java:263)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.cluster.service.BaseClusterService$ClusterServiceTaskBatcher$UpdateTask.run(BaseClusterService.java:1)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)


get "watcher_alarms-2017.12.11?pretty"
{
  "watcher_alarms-2017.12.11" : {
    "aliases" : { },
    "mappings" : {
      "report_admin" : {
        "properties" : {
          "@timestamp" : {
            "type" : "date"
          },
          "action" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "level" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "message" : {
            "type" : "object"
          },
          "payload" : {
            "type" : "object"
          },
          "report" : {
            "type" : "boolean"
          },
          "watcher" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "keyspace" : "watcher_alarms_2017_12_11",
        "number_of_shards" : "2",
        "provided_name" : "watcher_alarms-2017.12.11",
        "creation_date" : "1512953514915",
        "number_of_replicas" : "0",
        "uuid" : "k8GcMsXuQRm-QtvKBwx-Xg",
        "version" : {
          "created" : "5050099"
        }
      }
    }
  }
}

**Comment by sergibondarenko** [comment] 2017-12-11 08:40
@vroyer @lmangani 
Guys, ES doesn't allow to have different mappings for two fields with the same name under the same index. 

The possible solutions are:
1. Don't index field data, only store it. For this, you need to put `enabled: false` inside mapping. For example
```
    "transform": {
      "type": "object",
      "enabled": false
    }
```
But in this case, you can't query the not indexed data.
2. Rename one of the fields, and you can have a different mapping for it.
3. Put one of the fields in a different index.

Here is a reply from a ES developer https://discuss.elastic.co/t/are-not-allow-to-have-the-same-field-name-in-different-elastic-types-with-differents-types-string-nested-json-number-what-would-be-the-solution-with-elastic-search-for-this-issue/73914/2

**Comment by vroyer** [comment] 2017-12-11 10:07
Hi Sergii, Lorenzo

Finally, it work’s fine in elassandra (the issue was coming from a wrong mapping generated when the bug was not yet fixed).
This only limitation comes from Cassandra with table name < 48 characters, so sentinel action names should be shorter than 11 characters, because for each action definition, sentinl defines an ES type <random>_<action_name> mapped to a cassandra table.

Let me know if it’s okay from your side, it would be a great to support sentinl+elassandra !
Thanks,
Vincent.

**Comment by lmangani** [comment] 2017-12-11 10:45
Thank You so much, Vincent! I'm excited to get this working. 
We'll implement a limiter for the name lengths in SENTINL and confirm here with a full blown execution. Shall I rebuild from the patch branch to confirm or will this fix be merged back in 5.5.0.8?

**Comment by vroyer** [comment] 2017-12-11 11:59
So am i ! You can build from the dedicated branch and i will merge-it to quickly release 5.5.0.9 everything works fine for you.

**Comment by lmangani** [comment] 2017-12-11 23:45
Seems to work with the patched Elassandra and with SENTINL ids shortened as you suggested. Will do some deeper testing tomorrow but definitely a GO and looking forward to 5.5.0.9 :) Thansk @vroyer 

To reproduce w/ stock SENTINL:
```
sed -Ei "s/substr(2, 100)/substr(2, 3)/g" ${KIBANA_PLUGIN_PATH}/sentinl/public/services/watcher.js
```

![ezgif com-optimize 32](https://user-images.githubusercontent.com/1423657/33859729-8d0b6fdc-ded5-11e7-853f-355a0035d447.gif)

**Comment by vroyer** [comment] 2017-12-12 07:49
Fine !
As explain in a previous mail, i have a glitch when SSL+Authentication are in place on elasticsearch (traces in my mail).
Does sentinl work properly with the Pack or search guard with authentication ?
Thanks.
Vincent Royer
vroyer@strapdata.com
+33 7 83 18 25 40
http://www.strapdata.com

**Comment by lmangani** [comment] 2017-12-12 09:52
Let's arrange a small workshop, we can iron out all those issues and preferences out together?

**Comment by lmangani** [comment] 2017-12-12 09:57
@vroyer SG should work with the right configs: https://github.com/sirensolutions/sentinl/wiki/SENTINL-FAQ#q-how-can-i-use-sentinl-with-searchguard-authentication

**Closed as completed** 2018-01-06 15:10 UTC
