### ISSUE TITLE
Map of UDT of Cassandra not able to insert records.

### ISSUE THREAD

**Issue by infoankitp** [strapdata/elassandra#224] opened 2018-09-11 12:52 UTC
Hi 
I am not able to insert new records in a Cassandra table using mapping of Elastic Search. I am getting the below mentioned Error : 

```
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[127.0.0.1][127.0.0.1:9300][indices:data/write/bulk[s][p]]"}],"type":"runtime_exception","reason":"java.lang.IllegalArgumentException: Rejecting mapping update to [test_table] as the final mapping would have more than 1 type: [test_table, 510850]","caused_by":{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [test_table] as the final mapping would have more than 1 type: [test_table, 510850]"}},"status":500}
```

When creating an auto mapping, Elassandra was not able to create the complete mapping of the type of the UDT. 
```
curl -XGET "localhost:9200/test_table/_mapping" 

{
  "test_table": {
    "mappings": {
      "test_table": {
        "properties": {
          
          "abc_1": {
            "type": "long",
            "cql_collection": "singleton",
            "cql_partition_key": true,
            "cql_primary_key_order": 0
          },
          "abc_2": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_3": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_4": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_5": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_6": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_7": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_8": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_9": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "custom_map": {
            "type": "nested",
            "cql_struct": "map",
            "cql_collection": "singleton"
          }
        }
      }
    }
  }
}
```

While the actual mapping I needed was something like this :

```
curl -XPUT "http://localhost:9200/test_table" -H 'Content-Type: application/json' -d '{
   "settings": {
     "keyspace": "test_table"
   },
   "mappings": {
     "test_table": {
 
       "properties": {
         "abc_1": {
           "type": "long",
            "cql_collection": "singleton", 
            "cql_partition_key" : true, 
            "cql_primary_key_order" : 0
         },"abc_2": {
           "type": "long", 
       "cql_collection": "singleton"
         },
 
      "abc_3": {
           "type": "long", 
      "cql_collection": "singleton"
         },
         "abc_4": {
           "type": "long", 
      "cql_collection": "singleton"
         },
         "abc_5": {
           "type": "long", 
      "cql_collection": "singleton"
         },
         "abc_6": {
           "type": "long", 
     "cql_collection": "singleton"
         },
         "abc_7": {
          "type": "long", 
       "cql_collection": "singleton"
         },
         "abc_8": {
           "type": "long", 
      "cql_collection": "singleton"
         },
         "abc_1": {
           "type": "long", 
      "cql_collection": "singleton"
         },
         "custom_map": {
           "type": "object",
           "cql_struct": "map",
           "cql_collection": "singleton",
           "properties": {
             "custom_map_key": {
               "type": "text"
             },
             "custom_type": {
              "type": "object",
               "cql_struct": "udt",
               "cql_collection": "singleton",
               "cql_udt_name": "test_keyspace_custom_type",
               "properties": {
                 "custom_type_1": {
                   "type": "long"
                 },
                 "custom_type_2": {
                  "type": "long"
                 },
                 "custom_type_3": {
                   "type": "long"
                 },
                "custom_type_4": {
                   "type": "long"
                },
                 "custom_type_5": {
                   "type": "long"
                 },
                 "custom_type_6": {
                   "type": "long"
                 },
                 "custom_type_7": {
                   "type": "date"
                 },
                 "custom_type_8": {
                   "type": "text"
                 },
                 "custom_type_9": {
                   "type": "integer"
                 },
                 "custom_type_10": {
                   "type": "text"
                 },
                 "custom_type_11": {
                   "type": "text"
                 },
                 "custom_type_12": {
                   "type": "text"
                 },
                 "custom_type_13": {
                   "type": "text"
                 },
                 "custom_type_14": {
                   "type": "date"
                 },
                 "custom_type_15": {
                   "type": "text"
                 },
                 "custom_type_16": {
                   "type": "text"
                 },
                 "custom_type_17": {
                   "type": "long"
                 }
               }
             }
           }
         }
       }
     }
   }
 }'
```

Elastic confirmed the mapping is good to go!

```
curl -XGET "localhost:9200/test_table/?pretty=true"
```
 {
  "test_table": {
    "aliases": {},
    "mappings": {
      "test_table": {
        "properties": {
         
          "abc_1": {
            "type": "long",
            "cql_collection": "singleton",
            "cql_partition_key": true,
            "cql_primary_key_order": 0
          },
           "abc_2": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_3": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_4": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_5": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_6": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_7": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_8": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "abc_9": {
            "type": "long",
            "cql_collection": "singleton"
          },
          "custom_map": {
            "cql_struct": "map",
            "cql_collection": "singleton",
            "properties": {
              "custom_map_key": {
                "type": "text"
              },
              "custom_type": {
                "cql_collection": "singleton",
                "cql_udt_name": "test_table_custom_type",
                "properties": {
                  "custom_type_1": {
                    "type": "long"
                  },
                  "custom_type_2": {
                    "type": "text"
                  },
                  "custom_type_3": {
                    "type": "text"
                  },
                  "custom_type_4": {
                    "type": "date"
                  },
                  "custom_type_5": {
                    "type": "text"
                  },
                  "custom_type_6": {
                    "type": "long"
                  },
                  "custom_type_7": {
                    "type": "text"
                  },
                  "custom_type_8": {
                    "type": "long"
                  },
                  "custom_type_9": {
                    "type": "integer"
                  },
                  "custom_type_10": {
                    "type": "date"
                  },
                  "custom_type_11": {
                    "type": "long"
                  },
                  "custom_type_12": {
                    "type": "text"
                  },
                  "custom_type_13": {
                    "type": "text"
                  },
                  "custom_type_14": {
                    "type": "long"
                  },
                  "custom_type_15": {
                    "type": "long"
                  },
                  "custom_type_16": {
                    "type": "long"
                  },
                  "custom_type_17": {
                    "type": "text"
                  }
                }
              }
            }
          }
        }
      }
    },
    "settings": {
      "index": {
        "keyspace": "test_table",
        "number_of_shards": "1",
        "provided_name": "test_table",
        "creation_date": "1536666080082",
        "number_of_replicas": "2",
        "uuid": "3h0eEXEVRY2mYZRaTiNqDg",
        "version": {
           "created": "6020399"
         }
       }
     }
   }
 } 

And on  searching the data it is also searching the correct data but it is just not inserting the data using the elastic API.

Looking forward to hear from you regarding the same.

**Comment by DBarthe** [comment] 2018-09-13 03:32
Hello @infoankitp,

Could you please provide the insert curl request that failed, as well as the cassandra schema if possible and the version number so I can reproduce the issue.

I guess when you write using the elasticsearch api you're missing the type name in the url path, you should write something like `curl -X PUT localhost:9200/test_table/test_table/<id> -d "{....}"` since your keyspace and your table have the same name.

Thanks,

**Comment by infoankitp** [comment] 2018-09-13 16:09
I think I made a typo the keyspace's name is test_keyspace and the mapping I have done is of the table only. Also, Note that I am creating aliases here for the reference. Actual fields name and mapping is working fine, it is just the Insertion that is not working.
This is the Insert curl I am using 

``` 
curl -XPOST -H 'Content-Type: application/json' 'http://localhost:9200/test_table/_doc/' -d '{
	  "abc_1": 510850,
          "abc_2": 1536564065,
          "abc_3": 983,
          "abc_4": 62625,
          "abc_5": 101,
          "abc_6": 21596,
          "abc_7": 9808,
          "custom_map": {
            "101564476": {
              "custom_type_17": 61,
              "custom_type_5": 6,
              "custom_type_10": "Just a random Title",
              "custom_type_8": "Hey Buddy",
              "custom_type_4": 3,
              "custom_type_9": 1,
              "custom_type_6": 938,
              "custom_type_7": "2018-03-04T13:48:29.000Z",
              "custom_type_2": 938,
              "custom_type_1": 10156447638,
              "custom_type_3": 39,
	      "custom_type_11" : "null",
		"custom_type_12" : "null", 
		"custom_type_14" : "null", 
		"custom_type_13" : "null", 
		"custom_type_15"  : "null", 
		"custom_type_16" : "null"	
            }
          },
          "abc_8": 4740214,
          "abc_9": 9604397
  
}'
```

Please find below the Cassandra Schema : 
###### Schema for test_table Table 
```
CREATE TABLE test_keyspace.test_table (
    abc_1 bigint PRIMARY KEY,
    abc_2 bigint,
    abc_3 bigint,
    abc_4 bigint,
    abc_5 bigint,
    abc_6 bigint,
    abc_7 bigint,
    abc_8 bigint,
    abc_9 bigint,
    custom_map map<text, frozen<custom_type>>
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX elastic_test_table_idx ON test_keyspace.test_table () USING 'org.elassandra.index.ExtendedElasticSecondaryIndex';
```
###### Schema for UDT custom_type 
```
CREATE TYPE test_keyspace.custom_type (
    custom_type_1 bigint,
    custom_type_2 bigint,
    custom_type_3 bigint,
    custom_type_4 bigint,
    custom_type_5 bigint,
    custom_type_6 bigint,
    custom_type_7 timestamp,
    custom_type_8 text,
    custom_type_9 int,
    custom_type_10 text,
    custom_type_11 text,
    custom_type_12 text,
    custom_type_13 text,
    custom_type_14 timestamp,
    custom_type_15 text,
    custom_type_16 text,
    custom_type_17 bigint
);
```

**Comment by DBarthe** [comment] 2018-09-13 21:02
Hi,
You're right, seems Elassandra does not handle correctly UDTs inside map. It's not even mentioned in the documentation apparently. 
Thanks for reporting the issue

**Comment by DBarthe** [comment] 2018-09-13 21:22
Duplicate of #185

**Comment by DBarthe** [comment] 2018-09-13 21:22
I close the issue in favor of the older one.

**Closed as completed by DBarthe** 2018-09-13 21:22 UTC
Labels: bug
