### ISSUE TITLE
Performance issue : Latency when searching for data in Elassandra Cluster

### ISSUE THREAD

**Issue by prog-toolbox** [strapdata/elassandra#170] opened 2018-02-15 15:30 UTC
Elassandra : 5.5.0.10

JDK : 1.8

Hello,

I am trying to get data from my Elassandra Cluster, so I am using the SearchQuery from the Elasticsearch API. 
The problem that I obtain my results depending on the number nodes running on my cluster, which is composed of 5 nodes : 3 of them running as "Cassandra-Only" Nodes (located in a DataCenter) and the other 2 are running as "Cassandra+Elasticsearch" Nodes (located as well in another  DataCenter). 
So when I am searching in Elasticsearch, I am invoking the  SearchQuery on the 2 Nodes "Cassandra+Elasticsearch".
Here the results : 
             - Search Operation invoked when the 2 Nodes are UP : takes 4 seconds 
             - Search Operation invoked when only 1 Node is UP : takes 150 milliseconds 

I am asking why the search operation is taking so long when both nodes are UP ?

I appreciate your help.

**Comment by vroyer** [comment] 2018-02-16 09:11
Hi,
Yes there is an issue ! I guess your replication factor is 2 on the datacenter with Cassandra+Elasticsearch, for the keyspace where you search ?

There are many possible explanations (network issue, one of your two node is overloaded, your 2 nodes share the same hardware, the same disk with a bottleneck). I guess all is OK.

There was a bug fixed in version 5.5.0.11 involving performances (generated indices was bigger than needed for _all and _field_names), could you run the same test with version 5.5.0.12 (require index rebuild) or post more information to reproduce your issue ?
Thanks in advance.

**Comment by prog-toolbox** [comment] 2018-02-16 11:30
Hi,

My problem is fixed. I modified the value of "index.search_strategy_class":"RandomSearchStrategy".
It works effenciently and returns my data in few Millisenconds.
The solution is here : 

http://elassandra.readthedocs.io/en/v5.5.0.10/operations.html#optimizing-search-requests

There is a small issue though .. In the documentation, it is mentionned that I can update the value of "index.search_strategy_class" with the PUT method : 

curl -XPUT "http://localhost:9200/twitter/" -d '{
   "settings" : {
      "index.search_strategy_class":"RandomSearchStrategy"
   }
}'

But I wasn't able to do that. Actually, it returns the exception "index_already_exists_exception", so I deleted my index and I recreated it with the new settings.
My question is : Is there a way to update the index without the delete/create procedure ?

Again, Thank you for your help.

**Comment by vroyer** [comment] 2018-02-16 11:39
Yes, this is create index API, but you can dynamically update this setting like this (with _settings):

Your solution is a workaround, because with this strategy, the search is not more distributed on the 2 nodes but only on one. With what kind of search were you experiencing bad performances on a distributed search ? How many vnode do you have per node ?

curl -XPUT "http://localhost:9200/twitter/_settings" -d '{
"settings" : {
"index.search_strategy_class":"RandomSearchStrategy"
}
}'

**Comment by prog-toolbox** [comment] 2018-02-16 13:46
My application should maintain a high speed performance, regardless the number of alive nodes. 
In fact, I have exactly 2 Nodes (Cassandra+Elasticsearch) with a replication-factor = 2, so I am sure with this parameter, I will have the same data in Cassandra side between the 2 Nodes, and with the mapping mechanism between Cassandra and Elasticsearch, when I will invoke the search operation, I will obtain the same result regardless on which node I launched my request.
So as I said before, when I tried to update my index to modify the "index.search_strategy_class" with the value : "RandomSearchStrategy", using this request : 

curl -XPUT "http://localhost:9200/twitter/_settings" -d '{
"settings" : {
"index.search_strategy_class":"RandomSearchStrategy"
}
}'
It returned the "index_already_exists_exception":

{"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"index [my_index/jqiALRXnRwaB_Jvauaw1SA] already exists","index_uuid":"jqiALRXnRwaB_Jvauaw1SA","index":"my_index"}],"type":"index_already_exists_exception","reason":"index [my_index/jqiALRXnRwaB_Jvauaw1SA] already exists","index_uuid":"jqiALRXnRwaB_Jvauaw1SA","index":"my_index"},"status":400}[

That's why, I used the workaround : delete/create procedure.
Is there a fix to the PUT method ?

**Comment by vroyer** [comment] 2018-02-16 15:17
You URL was incorrect in your first mail, it must end by _settings to update an existing index. Here is successful update :

$ curl -XPUT "$http://$NODE:9200/gea/_settings" -d '{
    "settings" : {
    "index.search_strategy_class":"RandomSearchStrategy"
    }
}'
{"acknowledged":true}

I would like to understand why you had poor search performance with 2 nodes. What was your number of vnodes (or tokens) and what kind of search request did you run ?
Thanks in advance.

**Comment by prog-toolbox** [comment] 2018-02-16 16:24
I was following the official documentation which doesn't show "_settings" in the request.
Thank you and I appreciate your help, it works properly. At this stage, we can close this issue.
- Search Operation invoked when the 2 Nodes are UP : takes 200 milliseconds
- Search Operation invoked when only 1 Node is UP : takes 150 milliseconds

Concerning your question , I have 5 nodes and 256 tokens, and I run match queries.

**Closed as completed** 2018-02-22 23:23 UTC
